author: Theisen Sanders
description: The Markdown Note Taker
app_name: takingnote
version: Beta v0.1
angular: false  # Will need to be turned on page by page
exclude: ["vendor"]
google_analytics: UA-44002968-1